qc:
  adapter1: CTGTCTCTTATACACATCTCCGAGCCCACGAGACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG
  adapter2: CTGTCTCTTATACACATCTGACGCTGCCGACGANNNNNNNNGTGTAGATCTCGGTGGTCGCCGTATCATT

mapping:
  ref: grandis

refs:
  grandis: data/refs/grandis/Egrandis_v2.fasta


denovodist:
  kwip_sketchsize: 1e9
  mash_sketchsize: 1e5
  ksize: 21

sample_sets:

  noblank:
    - FDK10
    - J294
    - J296
    - J298
    - J301
    - J303
    - J307
    - J310
    - J311
    - J315
    - J316
    - J317
    - J318
    - J319
    - J320
    - J321g
    - J322
    - J324
    - J326
    - J327
    - J328
    - J329
    - J330
    - J331
    - J333
    - J333-plus
    - J333a
    - J334
    - J335
    - J338
    - J339
    - J340
    - J341
    - J342
    - J343
    - J344
    - J345
    - J345-plus
    - J346
    - J347
    - J348
    - J349
    - J350
    - J351
    - J351-plus
    - J352
    - J353
    - J354
    - J355
    - J355b
    - J357
    - J358
    - J359
    - J360
    - J361
    - J362-young
    - J363
    - J363-plus
    - J364
    - J365
    - J366
    - J366-plus
    - J367
    - J367i
    - J368
    - J369
    - J370
    - J371
    - J372
    - J373
    - J374
    - J375
    - J375-rep1
    - J376
    - J379
    - J381
    - J383
    - J385
    - J387
    - J389
    - J392
    - J393
    - J395
    - J397
    - J398
    - J399
    - J400
    - J401
    - J402
    - J403
    - J404
    - J405
    - J406
    - J407
    - J408
    - J411
    - J412
    - J413
    - J414
    - J416
    - J417
    - J418
    - J419
    - J420
    - J421
    - J422
    - J423
    - J424
    - J427
    - J427a
    - J431
    - J432
    - M1c
    - M2a
    - M2b
    - NAL05
    - NBJ30
    - NCD30
    - NCR13
    - NDU10
    - NE10467
    - NE25923
    - NE25953
    - NE35955
    - NE35959
    - NE36811
    - NE37169
    - NE37647
    - NE4583
    - NE67754
    - NE90535
    - RA1006
    - TLC715
    - TLC720
    - TLC725
    - TLC726
    - TLC775
    - VMA18
    - VMG14
    - VWG14

  nooutlier:
    - FDK10
    - J294
    - J296
    - J298
    - J301
    - J303
    - J307
    - J310
    - J311
    - J315
    - J316
    - J317
    - J318
    - J319
    - J320
    - J321g
    - J322
    - J324
    - J326
    - J327
    - J328
    - J329
    - J330
    - J331
    - J333
    - J333-plus
    - J333a
    - J334
    - J335
    - J338
    - J339
    - J340
    - J341
    - J342
    - J343
    - J344
    - J345
    - J345-plus
    - J346
    - J347
    - J348
    - J349
    - J350
    - J351
    - J351-plus
    - J352
    - J353
    - J355
    - J355b
    - J357
    - J358
    - J359
    - J360
    - J361
    - J362-young
    - J363
    - J363-plus
    - J364
    - J365
    - J366
    - J366-plus
    - J367
    - J367i
    - J368
    - J369
    - J370
    - J371
    - J372
    - J373
    - J374
    - J375
    - J375-rep1
    - J376
    - J379
    - J381
    - J383
    - J385
    - J387
    - J389
    - J392
    - J393
    - J395
    - J398
    - J399
    - J400
    - J401
    - J402
    - J403
    - J404
    - J405
    - J406
    - J407
    - J408
    - J411
    - J412
    - J413
    - J414
    - J416
    - J417
    - J418
    - J419
    - J420
    - J421
    - J422
    - J423
    - J424
    - J427
    - J427a
    - J431
    - J432
    - M1c
    - M2a
    - M2b
    - NCR13
    - NDU10
    - NE35955
    - RA1006
    - TLC715
    - TLC720
    - TLC725
    - TLC726
    - TLC775
    - VMA18
