qc:
  adapter1: CTGTCTCTTATACACATCTCCGAGCCCACGAGACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG
  adapter2: CTGTCTCTTATACACATCTGACGCTGCCGACGANNNNNNNNGTGTAGATCTCGGTGGTCGCCGTATCATT
  minqual: 25

mapping:
  aligners:
    - ngm
    - bwa
  ref: grandis

refs:
  grandis: /g/data1/xe2/references/eucalyptus/grandis/Egrandis_v2.fasta


denovodist:
  kwip_sketchsize: 1e9
  mash_sketchsize: 1e5
  ksize: 21

varcall:
  theta_prior: 0.02
  chunksize: 1000000
  aligners:
    # - ngm
    - bwa
  callers:
    #- freebayes
    - mpileup
  genomes:
    - grandis
  samplesets:
    - allsamples

angsd:
  mindepth: 10
  maxdepth: 1000
  minmapq: 30
  minq: 30
  snppval: 1e-3
  minind: 10
  minmaf: 0.02
  minMAD: 3 # Number of reads with minor alle
  glmethod: 2 # gatk
  aligners:
    - ngm
  genome: grandis
