qc:
  adapter1: CTGTCTCTTATACACATCTCCGAGCCCACGAGACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG
  adapter2: CTGTCTCTTATACACATCTGACGCTGCCGACGANNNNNNNNGTGTAGATCTCGGTGGTCGCCGTATCATT
  minqual: 25

sample_sets:
  - Project1
  - Project2
  - Oxley

mapping:
  aligners:
    - bwa
    #- ngm
    #- stampy
  refs:
    - grandisv2chl

refs:
  grandis: /g/data1/xe2/references/eucalyptus/grandis/Egrandis_v2.fasta
  grandisv2chl: /g/data1/xe2/references/eucalyptus/grandis_v2_chloro/Egrandis-v2-plus-chloro.fasta

chloro:
  genomes:
    - grandisv2chl
  aligners:
    - bwa

denovodist:
  kwip_sketchsize: 1e9
  mash_sketchsize: 1e5
  ksize: 21

varcall:
  theta_prior: 0.04 # based on mash
  chunksize: 10000000
  aligners:
    - bwa
  callers:
    #- freebayes
    - mpileup
  refs:
    - grandisv2chl
  samplesets:
    - Oxley
    - Project1
  filters:
    default: >
      -i 'QUAL >= 10 &&
          ALT != "." &&
          INFO/DP >= 5 &&
          INFO/AN >= 3'
    strict: >
      -i 'INFO/MQ >= 0 &&
          QUAL >= 40 &&
          ALT != "." &&
          INFO/DP >= 10 &&
          ((INFO/AN / N_SAMPLES)*2) > 0.50'
    # Above is presence rate, >50%

angsd:
  mindepth: 10
  maxdepth: 1000
  minmapq: 30
  minq: 10
  snppval: 1e-3
  minind: 10
  minmaf: 0.02
  minMAD: 3 # Number of reads with minor allel
  glmethod: 2 # gatk
  aligners:
    - bwa
  genome: grandisv2chl
